# Site settings
# Site title
title: CloudMount

# Site description
description: A fancy description of the site

# Site background
background: "images/dashboard.png"

# Site logo
logo: "images/logo.png"

# Countdown clock
# (This can be commented out if not required.)


# Mailing list subscription
# (This can be commented out if not required.)

# Social media links
# (This can be commented out if not required.)

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - README.md
   - COPYING.txt
